# Generated by Django 4.1.2 on 2022-10-14 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ViolationReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("blocked_uri", models.URLField()),
                ("disposition", models.CharField(max_length=12)),
                ("effective_directive", models.TextField()),
                ("original_policy", models.TextField()),
                ("violated_directive", models.TextField()),
                ("script_sample", models.CharField(max_length=40)),
                ("status_code", models.PositiveIntegerField()),
            ],
        ),
    ]
