# Generated by Django 4.1.2 on 2022-10-15 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("csp_tracker", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="violationreport",
            name="request_count",
            field=models.IntegerField(default=1),
        ),
    ]
