# Generated by Django 4.1.2 on 2022-10-14 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("csp_tracker", "0002_violationreport_document_uri_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="violationreport",
            name="referrer",
        ),
    ]
