# Generated by Django 4.1.2 on 2022-10-14 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("csp_tracker", "0004_violationreport_include_in_csp"),
    ]

    operations = [
        migrations.AddField(
            model_name="violationreport",
            name="csp_value",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
