# Generated by Django 4.1.3 on 2022-12-10 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("csp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CspReportBlacklist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "directive",
                    models.CharField(
                        choices=[
                            ("base-uri", "base-uri"),
                            ("child-src", "child-src"),
                            ("connect-src", "connect-src"),
                            ("default-src", "default-src"),
                            ("font-src", "font-src"),
                            ("form-action", "form-action"),
                            ("frame-ancestors", "frame-ancestors"),
                            ("frame-src", "frame-src"),
                            ("img-src", "img-src"),
                            ("manifest-src", "manifest-src"),
                            ("media-src", "media-src"),
                            ("object-src", "object-src"),
                            ("report-to", "report-to"),
                            ("report-uri", "report-uri"),
                            ("script-src", "script-src"),
                            ("script-src-attr", "script-src-attr"),
                            ("script-src-elem", "script-src-elem"),
                            ("style-src", "style-src"),
                            ("style-src-attr", "style-src-attr"),
                            ("style-src-elem", "style-src-elem"),
                            ("worker-src", "worker-src"),
                        ],
                        max_length=50,
                    ),
                ),
                ("blocked_uri", models.URLField()),
            ],
            options={
                "verbose_name": "CSP Blacklist",
                "verbose_name_plural": "CSP Blacklist",
                "ordering": ["directive", "blocked_uri"],
                "unique_together": {("directive", "blocked_uri")},
            },
        ),
    ]
